# Generated by Django 4.2rc1 on 2023-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pir',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pr',
            name='type',
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('DHT', 'Temperature and humidity'), ('PIR', 'Motin detection'), ('PR', 'Pressure sensor')], default=1, max_length=3, verbose_name='Sensor type'),
            preserve_default=False,
        ),
    ]
