# Generated by Django 4.2rc1 on 2023-03-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_dht_type_remove_pir_type_remove_pr_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='garage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensors.garage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensors.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pir',
            name='action_datetime',
            field=models.DateTimeField(),
        ),
    ]
